Farfetch/kafkaflow

README.md
=> Fix typo on readme file on Usage section

src/KafkaFlow.Abstractions/Configuration/IClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs
Add support to create a producer passing the producer type instance.
=> feat: add overload to create a producer passing the type instance

src/KafkaFlow.Abstractions/IDependencyResolver.cs, src/KafkaFlow.Microsoft.DependencyInjection/MicrosoftDependencyResolver.cs, src/KafkaFlow.Unity/UnityDependencyResolver.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/KafkaConfigurationBuilder.cs, src/KafkaFlow/Configuration/KafkaFlowConfigurator.cs, src/KafkaFlow/KafkaBus.cs, src/KafkaFlow/Producers/IProducerManager.cs, src/KafkaFlow/Producers/ProducerAccessor.cs
Since the producers are a dependency for other classes, it should be registered before in the container to avoid the problem on resolve a producer that is not registered yet.
=> fix: producer dependency chain

.gitignore, CODE_OF_CONDUCT.md, README.md, docs/di-containers.md
=> docs: better readme description and di-container page

src/KafkaFlow.Abstractions/IDependencyResolver.cs, src/KafkaFlow.Microsoft.DependencyInjection/MicrosoftDependencyResolver.cs, src/KafkaFlow.Unity/UnityDependencyResolver.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/KafkaConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerConfiguration.cs, src/KafkaFlow/Producers/MessageProducer.cs, src/KafkaFlow/Producers/ProducerAccessor.cs
=> fix: producer not working with Unity and with no default topic

samples/KafkaFlow.Admin.WebApi.Sample/KafkaFlow.Admin.WebApi.Sample.csproj, samples/KafkaFlow.Admin.WebApi.Sample/Program.cs, samples/KafkaFlow.Admin.WebApi.Sample/Properties/launchSettings.json, samples/KafkaFlow.Admin.WebApi.Sample/Startup.cs, samples/KafkaFlow.Admin.WebApi.Sample/appsettings.Development.json, samples/KafkaFlow.Admin.WebApi.Sample/appsettings.json, samples/KafkaFlow.Sample/Program.cs, src/KafkaFlow.Admin.WebApi/Contracts/ChangeWorketCountRequest.cs, src/KafkaFlow.Admin.WebApi/Contracts/GroupResponse.cs, src/KafkaFlow.Admin.WebApi/Contracts/ResetOffsetsRequest.cs, src/KafkaFlow.Admin.WebApi/Contracts/RewindOffsetsToDateRequest.cs, src/KafkaFlow.Admin.WebApi/Controllers/ConsumersController.cs, src/KafkaFlow.Admin.WebApi/Controllers/GroupsController.cs, src/KafkaFlow.Admin.WebApi/KafkaFlow.Admin.WebApi.csproj, src/KafkaFlow.Admin/Handlers/ChangeConsumerWorkersCountHandler.cs, src/KafkaFlow.Admin/Handlers/RestartConsumerByNameHandler.cs, src/KafkaFlow.Admin/Messages/ChangeConsumerWorkerCount.cs, src/KafkaFlow.Admin/Messages/RestartConsumerByName.cs, src/KafkaFlow.sln
Creates new KafkaFlow.Admin.WebApi packages with ConsumersController and GroupsController
Creates KafkaFlow.Admin.WebApi.Sample to demonstrate how to use it
=> feat: creates project Admin.WebApi

src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs
Merge ConsumerConfig and KafkaFlow fluent configuration
=> fix: merge ConsumerConfig with KF config

.github/workflows/build-pull-request.yml, src/Directory.Build.props, src/KafkaFlow.Abstractions/Extensions/DependencyConfiguratorExtensions.cs, src/KafkaFlow.Compressor/ConfigurationBuilderExtensions.cs, src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.IntegrationTests/Core/TraceLogHandler.cs, src/KafkaFlow.Serializer/ConfigurationBuilderExtensions.cs, src/KafkaFlow.UnitTests/MessageHeadersTests.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/ConsumerMiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/KafkaConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerMiddlewareConfigurationBuilder.cs, src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Producers/MessageProducer.cs
=> DI bug fixes and better producer recover

src/KafkaFlow.Abstractions/Configuration/IClusterConfigurationBuilder.cs, src/KafkaFlow.Abstractions/Configuration/SaslMechanism.cs, src/KafkaFlow.Abstractions/Configuration/SecurityInformation.cs, src/KafkaFlow.Abstractions/Configuration/SecurityProtocol.cs, src/KafkaFlow.Abstractions/Configuration/SslEndpointIdentificationAlgorithm.cs, src/KafkaFlow/Configuration/ClusterConfiguration.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerConfigurationBuilder.cs, src/KafkaFlow/Extensions/ConfigurationExtensions.cs
Adds method WithSecurityInfomation in cluster configuration to allow clients to use authentication
=> feat: adds authentication support

src/KafkaFlow/Consumers/KafkaConsumer.cs
Fixes consumer's SetErrorHandler registration
=> fix: calls SetErrorHandler only one time

src/KafkaFlow.Abstractions/Configuration/IConsumerConfigurationBuilder.cs, src/KafkaFlow.Abstractions/Configuration/IProducerConfigurationBuilder.cs, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerConfiguration.cs, src/KafkaFlow/Configuration/ProducerConfigurationBuilder.cs, src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Producers/MessageProducer.cs
This PR adds support for handling producer/consumer statistics.
Fixes #91 
Added the handlers in the sample project to make sure they get called with the producer/consumer statistics.
=> feat: adds support for statistics handlers

samples/KafkaFlow.Sample/Program.cs, src/KafkaFlow/Producers/BatchProduceExtension.cs
Creates a helper method (BatchProduceAsync()) to handle many produces and returns a promise that is completed when all requests are completed
=> feat: create BatchProduceAsync method

src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IKafkaConsumer.cs, src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Consumers/MessageConsumer.cs, src/KafkaFlow/Consumers/MessageContextConsumer.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs, src/KafkaFlow/KafkaBus.cs
=> refactor: consumer classes refactor

src/KafkaFlow.Abstractions/KafkaFlow.Abstractions.csproj, src/KafkaFlow.Admin.WebApi/KafkaFlow.Admin.WebApi.csproj, src/KafkaFlow.Admin/KafkaFlow.Admin.csproj, src/KafkaFlow.Compressor.Gzip/KafkaFlow.Compressor.Gzip.csproj, src/KafkaFlow.Compressor/KafkaFlow.Compressor.csproj, src/KafkaFlow.LogHandler.Console/KafkaFlow.LogHandler.Console.csproj, src/KafkaFlow.Microsoft.DependencyInjection/KafkaFlow.Microsoft.DependencyInjection.csproj, src/KafkaFlow.Serializer.Json/KafkaFlow.Serializer.Json.csproj, src/KafkaFlow.Serializer.NewtonsoftJson/KafkaFlow.Serializer.NewtonsoftJson.csproj, src/KafkaFlow.Serializer.ProtoBuf/KafkaFlow.Serializer.ProtoBuf.csproj, src/KafkaFlow.Serializer/KafkaFlow.Serializer.csproj, src/KafkaFlow.TypedHandler/KafkaFlow.TypedHandler.csproj, src/KafkaFlow.Unity/KafkaFlow.Unity.csproj, src/KafkaFlow/KafkaFlow.csproj
Add a nuget package icon in all projects but samples or test projects.
Fixes https://github.com/Farfetch/kafka-flow/issues/15
=> chore: add nuget package icon

src/KafkaFlow.Extensions.Hosting/KafkaFlow.Extensions.Hosting.csproj, src/KafkaFlow.Extensions.Hosting/KafkaFlowHostedService.cs, src/KafkaFlow.Extensions.Hosting/ServiceCollectionExtensions.cs, src/KafkaFlow.sln
Helper method to run KafkaFlow as a hosted service
=> feat: creates KafkaFlow.Extensions.Hosting to run as Hosted Service

src/KafkaFlow.TypedHandler/AssemblyInfo.cs, src/KafkaFlow.TypedHandler/HandlerTypeMapping.cs, src/KafkaFlow.TypedHandler/KafkaFlow.TypedHandler.csproj, src/KafkaFlow/Consumers/WorkerPoolFeeder.cs
-  Fix reset consumer offset is throwing ObjectDisposedException
-  Change HandlerTypeMapping to internally use a LinkedList
Fixes #128 
=> fix: reset consumer offset is throwing ObjectDisposedException

README.md
better indentation on readme basic usage
=> docs: better identation on readme basic usage

src/KafkaFlow.UnitTests/Consumer/WorkerPoolFeederTests.cs, src/KafkaFlow/Consumers/WorkerPoolFeeder.cs
fix StopAsync_WaitingOnConsumeWithCancellation_MustStop test case
=> test: fix StopAsync_WaitingOnConsumeWithCancellation_MustStop test case

README.md
=> chore: update slack channel invitation

src/KafkaFlow/ConsumerManagerFactory.cs, src/KafkaFlow/Consumers/Consumer.cs
After the consumer refactor the CustomFactory was not in use to create a new consumer
using automated tests
=> fix: fix consumer custom factory has no effect

src/KafkaFlow/Consumers/ConsumerFlowManager.cs, src/KafkaFlow/Consumers/ConsumerFlowStatus.cs, src/KafkaFlow/Consumers/IConsumerFlowManager.cs, src/KafkaFlow/Consumers/IMessageConsumer.cs, src/KafkaFlow/Consumers/MessageConsumer.cs
Creates the FlowStatus property on Consumer
Unit and Integration tests
=> feat: creates the FlowStatus property on Consumer

src/KafkaFlow/Configuration/IConsumerConfiguration.cs, src/KafkaFlow/Configuration/MiddlewareConfiguration.cs, src/KafkaFlow/ConsumerManagerFactory.cs, src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/IConsumer.cs, src/KafkaFlow/Consumers/IConsumerFlowManager.cs, src/KafkaFlow/Delegates.cs
Change consumer factory to use the  KafkaFlow IConsumer interface
=> feat: change consumer factory to use the  KafkaFlow IConsumer interface

src/KafkaFlow.Admin.WebApi/Adapters/ConsumerResponseAdapter.cs, src/KafkaFlow.Admin/TelemetryScheduler.cs, src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/ConsumerFlowManager.cs, src/KafkaFlow/Consumers/ConsumerStatus.cs, src/KafkaFlow/Consumers/IConsumer.cs, src/KafkaFlow/Consumers/IConsumerFlowManager.cs, src/KafkaFlow/Consumers/IMessageConsumer.cs, src/KafkaFlow/Consumers/MessageConsumer.cs
=> refactor: move Status from FlowManager to Consumer

src/KafkaFlow.Admin.Dashboard/ClientApp/src/app/consumer/consumer.component.ts, src/KafkaFlow.Admin.Dashboard/ClientApp/src/app/home/home.component.html, src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/ConsumerFlowManager.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IConsumerFlowManager.cs
=> fix: change the FlowManager only when the partitions are assigned

src/KafkaFlow.Abstractions/Configuration/IConsumerMiddlewareConfigurationBuilder.cs, src/KafkaFlow.Abstractions/Configuration/IMiddlewareConfigurationBuilder.cs, src/KafkaFlow.Abstractions/Configuration/IProducerMiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/ConsumerMiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/MiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerMiddlewareConfigurationBuilder.cs
Refactor the middleware configuration builder to use the same class to consumers and producers
Manually, unit and integration tests
=> refactor: refactor the middleware configuration builder

.github/workflows/build.yml, Makefile, src/KafkaFlow.IntegrationTests/SerializationTest.cs, src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, src/KafkaFlow.UnitTests/Serializers/NewtonsoftJsonSerializerTests.cs
Since this issue #191 were solved, I'm adding these tests to prevent behaviours regarding the differences between versions of the runtime.
=> test: add tests to NewtonsoftJsonSerializer

src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.Serializer/ConsumerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer/ProducerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer/SingleMessageTypeResolver.cs
=> feat: enable AddSingleTypeSerializer to receive a type parameter

src/KafkaFlow.Abstractions/Configuration/IMiddlewareConfigurationBuilder.cs, src/KafkaFlow.Abstractions/Extensions/DictionaryExtensions.cs, src/KafkaFlow.Abstractions/IDependencyResolver.cs, src/KafkaFlow.Abstractions/MiddlewareLifetime.cs, src/KafkaFlow.Admin.Dashboard/KafkaFlow.Admin.Dashboard.csproj, src/KafkaFlow.Microsoft.DependencyInjection/MicrosoftDependencyResolver.cs, src/KafkaFlow.TypedHandler/ConfigurationBuilderExtensions.cs, src/KafkaFlow.TypedHandler/TypedHandlerMiddleware.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/ConsumerConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/ProducerConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/Consumer/ConsumerManagerTests.cs, src/KafkaFlow.Unity/UnityDependencyResolver.cs, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/IConsumerConfiguration.cs, src/KafkaFlow/Configuration/IMiddlewareInstanceContainer.cs, src/KafkaFlow/Configuration/IProducerConfiguration.cs, src/KafkaFlow/Configuration/MiddlewareConfiguration.cs, src/KafkaFlow/Configuration/MiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/MiddlewareInstanceContainer.cs, src/KafkaFlow/Configuration/ProducerConfiguration.cs, src/KafkaFlow/ConsumerManagerFactory.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/IMiddlewareExecutor.cs, src/KafkaFlow/MiddlewareExecutor.cs, src/KafkaFlow/Producers/MessageProducer.cs
Adds the option to choose the middleware instance lifetime
Manually, Unit and Integration Tests
=> feat: adds the option to choose the middleware instance lifetime

src/KafkaFlow.Admin.Dashboard/ApplicationBuilderExtensions.cs, src/KafkaFlow.Admin.Dashboard/DashboardConfiguration.cs, src/KafkaFlow.Admin.Dashboard/DashboardConfigurationBuilder.cs, src/KafkaFlow.Admin.Dashboard/IDashboardConfigurationBuilder.cs
Allow configuring the dashboard endpoint and the dashboard request pipeline
=> feat: allow configuring the dashboard endpoint and the dashboard request pipeline

README.md
README update
N/A
-   [x] I have performed a self-review of my code
=> style: update README.md

src/KafkaFlow/Consumers/OffsetCommitter.cs
feat: log offsets committed successfully
=> log offsets committed successfully

src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/IConsumer.cs
creates a log entry when ConfluentClient error occurs
N/A
=> chore: creates a log entry when ConfluentClient error occurs

src/KafkaFlow.Abstractions/Extensions/DictionaryExtensions.cs, src/KafkaFlow/Consumers/OffsetManager.cs, src/KafkaFlow/MiddlewareExecutor.cs
Fix IndexOutOfRangeException on registering offset processed actions due to multithreading context
Manually, Unit and Integration Tests
=> fix: fix IndexOutOfRangeException on registering offset actions

src/KafkaFlow.Serializer/ConsumerMiddlewareConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer/ProducerMiddlewareConfigurationBuilder.cs
=> refactor: rename extension classes

.github/workflows/build.yml, .github/workflows/publish.yml, samples/KafkaFlow.Sample.FlowControl/KafkaFlow.Sample.FlowControl.csproj, samples/KafkaFlow.Sample.FlowControl/Program.cs, src/KafkaFlow.Abstractions/Configuration/IConsumerConfigurationBuilder.cs, src/KafkaFlow.Abstractions/ConsumerInitialState.cs, src/KafkaFlow.Admin/Handlers/PauseConsumersByGroupHandler.cs, src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, src/KafkaFlow.sln, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/IConsumerConfiguration.cs, src/KafkaFlow/Consumers/ConsumerManager.cs, src/KafkaFlow/Consumers/IMessageConsumer.cs, src/KafkaFlow/Consumers/MessageConsumer.cs, src/KafkaFlow/KafkaBus.cs
Enable client application start, stop and define the consumer initial state
=> Enable client application start, stop and define the consumer initial state

src/KafkaFlow.LogHandler.Microsoft/AssemblyInfo.cs, src/KafkaFlow.LogHandler.Microsoft/ExtensionMethods.cs, src/KafkaFlow.LogHandler.Microsoft/KafkaFlow.LogHandler.Microsoft.csproj, src/KafkaFlow.LogHandler.Microsoft/MicrosoftLogHandler.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/KafkaConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, src/KafkaFlow.UnitTests/LogHandlers/MicrosoftLogHandlerTests.cs, src/KafkaFlow.sln
=> feat(log): microsoft logging based log handler

src/KafkaFlow.Unity/UnityDependencyConfigurator.cs, src/KafkaFlow.Unity/UnityDependencyResolver.cs
fix ResolveAll() of unity container
Fixes #223 
=> fix: fix ResolveAll() of unity container

src/KafkaFlow.SchemaRegistry/KafkaFlow.SchemaRegistry.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf.csproj, src/KafkaFlow/KafkaFlow.csproj
Update confluent packages to version 1.9.0.
Due to https://issues.apache.org/jira/browse/AVRO-2633, already resolved in Apache. Avro version 1.11.0 (https://www.nuget.org/packages/Apache.Avro),
we need to update these packages above to use this version and fix the issue.
Fixes # ([issue](https://github.com/Farfetch/kafka-flow/issues/276))
TBD (this is a proposed solution to the improvement)
By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership …
=> feat: update confluent packages to version 1.9.0

src/KafkaFlow/Consumers/ConsumerWorkerPool.cs
Fix NullReferenceException when stopping the Bus
Fixes #256 
Manually and using automation
=> fix: fix NullReferenceException when stopping

docker-compose.yml, samples/KafkaFlow.Sample/Program.cs
Upgrade Kafka images versions to 7.X release in order to support Apple Silicon processors.
Fixes #289 
1. Run docker-compose.
2. Create a topic.
3. Run "KafkaFlow.Sample" sample.
4. Observe that messages are received by consumers.
=> Update docker-compose Kafka images versions

src/KafkaFlow/Producers/MessageProducer.cs
Allow produce tombstone message.
=> feat: allow produce tombstone message

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Configure Issue Templates to give a better experience to the contributor.
=> Add Issue Templates to repository

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, README.md
- Review README to reference the new docs website.
- Fix: Link to documentation on the issues config
- Contributing guidelines: Explain how to run tests
=> chore: review readme to reference new docs page

website/docs/guides/configuration.md, website/docs/guides/dependency-injection.md
Review Dependency Injection Guide.
=> chore: review dependency injection docs

src/KafkaFlow.SchemaRegistry/KafkaFlow.SchemaRegistry.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf.csproj, src/KafkaFlow/KafkaFlow.csproj
=> chore: update Confluent packages to 1.9.3

CONTRIBUTING.md
Add a clear section on what to do before opening a Pull Request.
=> chore: contribution guideline before opening a pr

website/docs/guides/middlewares/typed-handler-middleware.md
Add a section to the documentation explaining how Message Type is discovered when using Typed Handler Middleware.
Fixes #307 
=> docs: how message type is discovered #307

src/KafkaFlow.SchemaRegistry/AsyncSchemaRegistryTypeNameResolverWrapper.cs, src/KafkaFlow.SchemaRegistry/ConfluentDeserializerWrapper.cs, src/KafkaFlow.SchemaRegistry/ConfluentSerializerWrapper.cs, src/KafkaFlow.SchemaRegistry/IAsyncSchemaRegistryTypeNameResolver.cs, src/KafkaFlow.SchemaRegistry/SchemaRegistryTypeResolver.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/ConfluentAvroTypeNameResolver.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/ConsumerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/ProducerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/ConfluentProtobufTypeNameResolver.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/ConsumerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/ProducerConfigurationBuilderExtensions.cs, src/KafkaFlow.Serializer/AsyncMessageTypeResolverWrapper.cs, src/KafkaFlow.Serializer/IAsyncMessageTypeResolver.cs, src/KafkaFlow.Serializer/SerializerConsumerMiddleware.cs, src/KafkaFlow.Serializer/SerializerProducerMiddleware.cs, src/KafkaFlow.TypedHandler/HandlerExecutor.cs, src/KafkaFlow/Consumers/DistributionStrategies/BytesSumDistributionStrategy.cs
=> feat: async type resolvers

website/docs/introduction.md
Fix broken links targeting old wiki.
Fixes #351 
Run documentation.
=> docs: fix broken links

website/package-lock.json, website/package.json, website/src/pages/index.js, website/src/pages/index.module.css, website/yarn.lock
- Upgrade Docusaurus to 2.3.0.
- Add a video about KafkaFlow to the docs homepage.
=> docs: upgrade docusaurus to 2.3 and add video to homepage

src/KafkaFlow.Abstractions/Configuration/SecurityInformation.cs, src/KafkaFlow/Extensions/ConfigurationExtensions.cs
Add SslCaPem parameter to connect to kafka.
Fixes #378 
Connect to my cluster using this parameter
=> Add SslCaPem security information to connect to kafka

samples/KafkaFlow.Sample.PauseConsumerOnError/KafkaFlow.Sample.PauseConsumerOnError.csproj, samples/KafkaFlow.Sample.PauseConsumerOnError/MessageHandler.cs, samples/KafkaFlow.Sample.PauseConsumerOnError/PauseConsumerOnExceptionMiddleware.cs, samples/KafkaFlow.Sample.PauseConsumerOnError/Program.cs, samples/KafkaFlow.Sample.PauseConsumerOnError/WelcomeMessage.cs, src/KafkaFlow.sln, website/docs/getting-started/samples.md, website/docs/guides/middlewares/middlewares.md
Sample on how to pause a consumer and not commit offset when a message can't be processed.
=> docs: how to pause consumer if a message fails to be processed

website/docs/guides/admin/web-api.md
Review documentation so snippets use the `IConsumerAdmin` interface instead of the `IAdminProducer` interface that nowadays is internal.
Fixes #370 
=> docs: review code snippets

website/package.json, website/yarn.lock
=> docs: upgrade docusaurus to 2.4.0

src/KafkaFlow.UnitTests/OffsetCommitterTests.cs, src/KafkaFlow.UnitTests/PartitionOffsetsTests.cs
Fixes some flaky tests related to concurrent scenarios in offsets commit process
=> test: fixes some flaky unit tests

website/docs/guides/consumers/consumers.md, website/docs/guides/middlewares/batch-consume-middleware.md
Updates the documentation relative to Batch Consumer and the Max Poll Interval.
Fixes # https://github.com/Farfetch/kafkaflow/issues/395
Fixes # https://github.com/Farfetch/kafkaflow/issues/296
=> docs: Update Consumer Documentation

src/KafkaFlow.SchemaRegistry/KafkaFlow.SchemaRegistry.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf.csproj, src/KafkaFlow/KafkaFlow.csproj
This MR updates Confluent packages (Confluent.Kafka, Confluent.SchemaRegistry.*) to version 2.1.1.
Fixes #388 
Testing using the automated tests (unit and integration) in the project.
=> Update Confluent packages to 2.1.1

.github/workflows/build.yml, .github/workflows/deploy-website.yml, .github/workflows/publish.yml, .github/workflows/test-deploy-website.yml
Upgrade GitHub actions setup to the latest version:
- checkout
- setup-dotnet
=> chore: upgrade checkout and dotnet actions version

website/src/pages/extensions/index.js
Add [KafkaFlow Contrib](https://github.com/AlexeyRaga/kafkaflow-contrib) by @AlexeyRaga to the extensions list.
=> docs: list kafkaflow-contrib extension

samples/KafkaFlow.Sample.WildcardConsumer/KafkaFlow.Sample.WildcardConsumer.csproj, samples/KafkaFlow.Sample.WildcardConsumer/PrintConsoleMiddleware.cs, samples/KafkaFlow.Sample.WildcardConsumer/Program.cs, src/KafkaFlow.Abstractions/Configuration/IConsumerConfigurationBuilder.cs, src/KafkaFlow.sln, website/docs/getting-started/samples.md, website/docs/guides/consumers/add-consumers.md
This is a common question when building consumers: _"How to subscribe to multiple Kafka topics using wildcard patterns?"_
In this sample, it shows how to subscribe to all topics with a given prefix.
=> docs: sample using wildcard for a topic name

src/KafkaFlow.Serializer.ProtobufNet/KafkaFlow.Serializer.ProtobufNet.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro.csproj, tests/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj, tests/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj
Updates dependencies in order to no longer have any JFrog X-Ray audit issues
=> fix: Correct JFrog X-Ray audit issues

website/src/pages/community/index.js
List new community articles and videos.
=> docs: list new community resources

website/docs/guides/middlewares/middlewares.md
This PR adds a note informing developers to use overloads of Add method for middleware lifetime.
https://github.com/Farfetch/kafkaflow/pull/525/
NA
=> docs: update middlewares

Makefile, docker-compose.yml, src/KafkaFlow.LogHandler.Console/KafkaFlow.LogHandler.Console.csproj, src/KafkaFlow.LogHandler.Microsoft/KafkaFlow.LogHandler.Microsoft.csproj, src/KafkaFlow.Serializer.JsonCore/KafkaFlow.Serializer.JsonCore.csproj, tests/KafkaFlow.IntegrationTests/ProducerTest.cs
- Update the makefile to use the latest `docker compose` (instead of `docker-compose`)
- Update the makefile integration test not fixing the test in .netcore 3.1
- Update `System.Text.Json` to latest 6.x version to remove vulnerability
- Remove version from `docker-compose.yml` file
- Fix one integration test that was failing
By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership …
=> chore: update docker compose command

tests/KafkaFlow.IntegrationTests/Core/Handlers/MessageStorage.cs, tests/KafkaFlow.IntegrationTests/ProducerTest.cs
Fix ProduceNullMessageTest tests.
-   [X] I have added tests to cover my changes
=> fix(tests): fix ProduceNullMessageTest tests

src/KafkaFlow/Consumers/ConsumerWorker.cs
Super small change that adds partition and offset to error log.
Will be useful for debugging. Now it's quite difficult to figure out what message caused an error.
=> Enrich error log with partition and offset

samples/KafkaFlow.Sample.BatchOperations/KafkaFlow.Sample.BatchOperations.csproj, samples/KafkaFlow.Sample.ConsumerThrottling/KafkaFlow.Sample.ConsumerThrottling.csproj, samples/KafkaFlow.Sample.CooperativeSticky/KafkaFlow.Sample.CooperativeSticky.csproj, samples/KafkaFlow.Sample.FlowControl/KafkaFlow.Sample.FlowControl.csproj, samples/KafkaFlow.Sample.OpenTelemetry/KafkaFlow.Sample.OpenTelemetry.csproj, samples/KafkaFlow.Sample.PauseConsumerOnError/KafkaFlow.Sample.PauseConsumerOnError.csproj, samples/KafkaFlow.Sample.SchemaRegistry/KafkaFlow.Sample.SchemaRegistry.csproj, samples/KafkaFlow.Sample.WebApi/KafkaFlow.Sample.WebApi.csproj, samples/KafkaFlow.Sample.WildcardConsumer/KafkaFlow.Sample.WildcardConsumer.csproj, samples/KafkaFlow.Sample/KafkaFlow.Sample.csproj, src/KafkaFlow.Abstractions/KafkaFlow.Abstractions.csproj, src/KafkaFlow.Admin.Dashboard/KafkaFlow.Admin.Dashboard.csproj, src/KafkaFlow.Extensions.Hosting/KafkaFlow.Extensions.Hosting.csproj, src/KafkaFlow.LogHandler.Console/KafkaFlow.LogHandler.Console.csproj, src/KafkaFlow.LogHandler.Microsoft/KafkaFlow.LogHandler.Microsoft.csproj, src/KafkaFlow.Microsoft.DependencyInjection/KafkaFlow.Microsoft.DependencyInjection.csproj, src/KafkaFlow.OpenTelemetry/KafkaFlow.OpenTelemetry.csproj, src/KafkaFlow.Serializer.JsonCore/KafkaFlow.Serializer.JsonCore.csproj, src/KafkaFlow.Serializer.ProtobufNet/KafkaFlow.Serializer.ProtobufNet.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf.csproj, src/KafkaFlow/KafkaFlow.csproj, tests/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj, tests/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, website/docs/guides/migration/from-v2-to-v3.md, website/docs/guides/migration/from-v3-to-v4.md
- Update nuget packages
- Add v4 migration guide
Fixes #612
-   [X] I have made corresponding changes to the documentation
=> v4 migration guide
