Farfetch/kafkaflow

src/KafkaFlow/MessageHeaders.cs
Class MessageHeaders now is public.
Fixes #34 
Unit and integration tests were executed
=> fix: make MessageHeaders public

samples/KafkaFlow.Sample/Program.cs, src/KafkaFlow.UnitTests/OffsetManagerTests.cs, src/KafkaFlow.UnitTests/PartitionOffsetsTests.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/OffsetManager.cs, src/KafkaFlow/Consumers/PartitionOffsets.cs
Fix a bug in OffsetManager when we have topic/partition with offset gaps
We changed the unit tests to cover these cases and create a new one to simulate a concurrent scenario
=> fix: bug in OffsetManager with offset gaps

src/KafkaFlow/Consumers/MessageConsumer.cs
Using the KafkaFlow.Admin.WebApi it's possible to change the WorkerCount of a specific consumer.
Currently, there is no way to know how many workers are set to the consumer.
1. GET to API consumer endpoint (https://localhost:5001/kafka-flow/groups/TestGroup/consumers/TestConsumer)
=> fix: adds WorkerCount property to MessageConsumer

src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Producers/MessageProducer.cs
Currently we are logging all consumer or producer Kafka errors with severity 'Error'. There are non-fatal errors, like when a consumer is disconnected being logged as 'Error'. These are normal and expected "errors" when the consumer times out after no activity for 10 minutes (default).
This PR sets the log severity according to the error being fatal or non-fatal.
Fixes #89 …
=> Log Kafka errors according to severity

src/KafkaFlow.Admin/Extensions/ClusterConfigurationBuilderExtensions.cs
This Pull Request changes the way the application adds the consumer for KafkaFlow.Admin.
If the application needs to scale all machine hosts will have the same consumer group.
Fixes #93 
Running the project `KafkaFlow.Admin.WebApi.Sample`:
- Endpoint: https://localhost:5001/kafka-flow/groups
- Result:
=> feat: adds Assembly name and ramdom string to KafkaFlow admin consumer

src/KafkaFlow.Abstractions/Configuration/IConsumerMiddlewareConfigurationBuilder.cs, src/KafkaFlow/Configuration/ConsumerMiddlewareConfigurationBuilder.cs
This PR add support for middlewares to be registered to run before other middlewares.
Fixes #94 
Using the sample project and registering a middlewares first, then registering a second middleware using the AddAtBegining() method and make sure the second middleware is called first.
=> feat: allow middlewares to be registered at the beginning

src/KafkaFlow.Abstractions/IMessageContextConsumer.cs, src/KafkaFlow.UnitTests/MessageContextConsumerTests.cs, src/KafkaFlow/Consumers/MessageContextConsumer.cs
Access to message timestamp can be important for observability (e.g. monitoring) 
This Pull Request enables the access to the message timestamp from the Message Consumer Context.
- Unit test was created to make sure the MessageTimestamp is returned from the Kafka ConsumeResult
- Run the sample and checked that the message being consumed has the correct timestamp reported
=> feat: access message timestamp from message consumer context

src/KafkaFlow.LogHandler.Console/ConsoleLogHandler.cs
Today we have a problem serializing exception inside ConsoleLogHandler, this pull request changes how we serialize them to fix it.
=> fix: fix ConsoleLogHandler when serializing exceptions

src/KafkaFlow.Admin/Handlers/PauseConsumersByGroupTopicHandler.cs, src/KafkaFlow.Admin/Handlers/ResumeConsumersByGroupTopicHandler.cs, src/KafkaFlow.IntegrationTests/ConsumerTest.cs, src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.IntegrationTests/Core/Handlers/PauseResumeHandler.cs, src/KafkaFlow.UnitTests/MessageContextConsumerTests.cs, src/KafkaFlow/Configuration/KafkaFlowConfigurator.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IKafkaConsumer.cs, src/KafkaFlow/Consumers/IKafkaConsumerFlowManager.cs, src/KafkaFlow/Consumers/IMessageConsumer.cs, src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Consumers/KafkaConsumerFlowManager.cs, src/KafkaFlow/Consumers/MessageConsumer.cs, src/KafkaFlow/Consumers/MessageContextConsumer.cs, src/KafkaFlow/KafkaBus.cs, src/KafkaFlow/Producers/BatchProduceExtension.cs
Creates a background Task to send heartbeats to Kafka when the entire consumer is paused
Fixes #111 
=> fix: paused consumers send heartbeats

src/KafkaFlow.UnitTests/ConfigurationBuilders/ConsumerConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/ProducerConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/ProducerConfiguration.cs, src/KafkaFlow/Configuration/ProducerConfigurationBuilder.cs, src/KafkaFlow/Consumers/KafkaConsumer.cs, src/KafkaFlow/Delegates.cs, src/KafkaFlow/Extensions/ConfigurationBuilderExtensions.cs, src/KafkaFlow/KafkaBus.cs, src/KafkaFlow/Producers/MessageProducer.cs
Creates method WithCustomFactory() that allows the client app to use custom instances of producers and consumers.
Closes #107 
=> feat: allow client to use a custom producer and consumer factory

src/KafkaFlow.UnitTests/MessageContextConsumerTests.cs
UnitTest 'MessageContextConsumerTests.MessageTimestamp_ConsumeResultHasMessageTimestamp_ReturnsMessageTimestampFromResult' is failing because compares a local datetime with an UTC datetime.
Now the unit test is comparing both datetimes in the same format (UTC)
=> fix: compare both datetime values in UTC format

samples/KafkaFlow.Sample/Program.cs, src/KafkaFlow.Compressor.Gzip/GzipMessageCompressor.cs, src/KafkaFlow.Compressor/ConfigurationBuilderExtensions.cs, src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/ProducerConfigurationBuilderTests.cs, src/KafkaFlow/Configuration/ProducerConfigurationBuilder.cs, src/KafkaFlow/Extensions/ConfigurationBuilderExtensions.cs
This PR adds a [syntax sugar](https://en.wikipedia.org/wiki/Syntactic_sugar#:~:text=In%20computer%20science%2C%20syntactic%20sugar,style%20that%20some%20may%20prefer.) to use native compression available on the confluence driver and marks GzipMiddlewareCompressor as Deprecated.
Fixes https://github.com/Farfetch/kafka-flow/issues/130
Unit and integration tests 
=> feat: add native compression support

src/KafkaFlow.Serializer.Json/JsonMessageSerializer.cs, src/KafkaFlow.UnitTests/Consumer/WorkerPoolFeederTests.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/WorkerPoolFeeder.cs
This project looks great! I've looked through some of the code and spotted a couple of improvements.
- Use `System.Text.Json` UTF8 memory overloads to reduce unnecessary string copying.
- The `WorkerPoolFeeder` start task was never really being stopped properly when the stop method was called. Stop was basically a no-op so the tests would finish immediately and the mock verification would pass when then should have been failing. Stopping could rely entirely on cooperative cancellation, and the `WithCancellation` stuff could be removed (it seems overkill to me), however that's a change in behaviour and we'd probably want to delete a couple of tests.
I've ran the unit tests, which cover the area of code that has been changed.
-   [x] My code follows the style guidelines of …
=> Improve JSON Memory Usage & Fix Async Startup Behaviour

src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.TypedHandler/TypedHandlerConfigurationBuilder.cs
Add a new `AddHandlersFromAssemblyOf` that accepts multiple marker types.
Fixes #147 
Changed the `Bootstrapper` class in the integration tests to use the new method.
=> feat: add AddHandlersFromAssemblyOf that accepts multiple marker types

src/KafkaFlow.Compressor.Gzip/GzipMessageCompressor.cs, src/KafkaFlow.Compressor/ConfigurationBuilderExtensions.cs
GZIP middleware compressor shouldn't be used anymore but in cases where consumers are receiving messages compressed with it.
The native compression (producer.WithCompression()) should be used instead and this PR marks the GZIP middleware compressor as Obsolete to be able to delete it on v3.
=> refactor: mark gzip compressor as obsolete

src/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj, src/KafkaFlow/Producers/BatchProduceExtension.cs, src/KafkaFlow/Producers/BatchProduceItem.cs, src/KafkaFlow/Producers/IMessageProducer.cs, src/KafkaFlow/Producers/MessageProducer.cs, src/KafkaFlow/Producers/MessageProducerWrapper.cs
The IMessageProducer was changed to allow the message key to be passed as an object and be encoded or serialized by the client application.
Fixes #153 
Unit and Integration tests were executed
=> feat(producer): change Produce and ProduceAsync to receive the message key as object

src/KafkaFlow.UnitTests/ConfigurationBuilders/ConsumerConfigurationBuilderTests.cs, src/KafkaFlow.UnitTests/Consumer/ConsumerManagerTests.cs, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/IConsumerConfiguration.cs, src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/ConsumerManager.cs, src/KafkaFlow/Consumers/IConsumer.cs, src/KafkaFlow/Extensions/ConfigurationBuilderExtensions.cs
Added configuration methods to allow clients to implement some tasks when Kafka events partitions assigned and revoked occur
Fixes #170
Was complemented the existents tests.
=> feat: expose partitions assigned and revoked events

src/KafkaFlow.Serializer.NewtonsoftJson/NewtonsoftJsonSerializer.cs
fixes NewtonsoftJsonSerializer wrongly closing streams
=> fix: fixes NewtonsoftJsonSerializer wrongly closing streams

src/KafkaFlow.Admin.WebApi/KafkaFlow.Admin.WebApi.csproj
KafkaFlow.Admin.WebApi is not being published since version 1.5.6. 
This PR fixes it by setting the project KafkaFlow.Admin.WebApi as packable.
=> fix: set KafkaFlow.Admin.WebApi as packable

src/KafkaFlow.Compressor/CompressorConsumerMiddleware.cs, src/KafkaFlow.Compressor/CompressorProducerMiddleware.cs
When compressing the message with any CompressorProducerMiddleware, the partition key is being overwritten with the message value.
This PR fixed this issue.
=> fix: avoid to loss partition key when compressing

src/KafkaFlow.Serializer.NewtonsoftJson/NewtonsoftJsonSerializer.cs
NewtonsoftJsonSerializer is not working properly with versions previous than V2
=> fix: fixes retro-compatibility on NewtonsoftJsonSerializer

src/KafkaFlow.Admin.WebApi/Controllers/ConsumersController.cs, src/KafkaFlow.Admin.WebApi/Controllers/GroupsController.cs, src/KafkaFlow.Admin.WebApi/Controllers/TelemetryController.cs
In order to avoid magic strings on web api routes, this PR uses action name as route name on web api endpoints
=> refactor: use action name as route name on webapi

src/KafkaFlow.Admin.Dashboard/ApplicationBuilderExtensions.cs
Allow to define the dashboard path.
Until now, the dashboard path is always `/kafka-flow` and it
does not exist any method to change the configuration
=> Allow to define the dashboard path

src/KafkaFlow.UnitTests/OffsetCommitterTests.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs
This PR fixes an issue where the framework would not retry committing offsets after a failure.
Fixes #213 
Added unit tests.
=> fix: requeue failed offsets

src/KafkaFlow.UnitTests/OffsetCommitterTests.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs
This PR fixes an issue where the framework would not retry committing offsets after a failure.
Fixes #213 
Added unit tests.
=> fix: requeue failed offsets (v1)

src/KafkaFlow.Abstractions/ISerializerContext.cs, src/KafkaFlow.Abstractions/SerializerContext.cs, src/KafkaFlow.SchemaRegistry/ConfluentDeserializerWrapper.cs, src/KafkaFlow.SchemaRegistry/ConfluentSerializerWrapper.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentAvro/ConfluentAvroSerializer.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson/ConfluentJsonSerializer.cs, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/ConfluentProtobufSerializer.cs, src/KafkaFlow.Serializer/SerializerConsumerMiddleware.cs, src/KafkaFlow.Serializer/SerializerProducerMiddleware.cs, src/KafkaFlow.UnitTests/Serializers/SerializerConsumerMiddlewareTests.cs, src/KafkaFlow.UnitTests/Serializers/SerializerProducerMiddlewareTests.cs
Added topic property to ISerializerContext to make topic available to ConfluentSerializerWrapper and ConfluentDeserializerWrapper.  This allows for the topic name to be used to build the subject name for a schema when using the Topic or TopicRecord subject name strategies.
Fixes #216 
I ran the KafkaFlow.Sample.Avro project with the topic, record, and topicrecord subject naming strategies.  I verified that in each case, 
- messages were produced and consumed properly
- schemas were added to the schema registry under the expected subject names.
By sending us your …
=> fix: fix schema subject names for Topic and TopicRecord strategies

samples/KafkaFlow.Sample/Program.cs, src/KafkaFlow.Abstractions/Configuration/IClusterConfigurationBuilder.cs, src/KafkaFlow.UnitTests/OffsetCommitterTests.cs, src/KafkaFlow.UnitTests/OffsetManagerTests.cs, src/KafkaFlow.UnitTests/PartitionOffsetsTests.cs, src/KafkaFlow/Configuration/ConsumerConfiguration.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs, src/KafkaFlow/Configuration/IConsumerConfiguration.cs, src/KafkaFlow/ConsumerManagerFactory.cs, src/KafkaFlow/Consumers/ConsumerContext.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IOffsetCommitter.cs, src/KafkaFlow/Consumers/IOffsetManager.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs, src/KafkaFlow/Consumers/OffsetManager.cs, src/KafkaFlow/Consumers/PartitionOffsets.cs, src/KafkaFlow/Extensions/ConfigurationBuilderExtensions.cs
Adds a handler to be executed when the consumer has pending offsets to be committed
Unit tests were created
=> feat: Pending offsets handler

src/KafkaFlow.SchemaRegistry/ClusterConfigurationBuilderExtensions.cs
In order to avoid the ISchemaRegistryClient being disposed, now it is using lifetime = singleton when injecting this dependency
Fixes #230 
=> fix: use just a single instance of ISchemaRegistryClient

src/KafkaFlow.Admin/MemoryTelemetryStorage.cs
Hello. We are getting these exceptions in out monitoring service:
```
Error executing consumer: {"Message":redacted}
ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at KafkaFlow.Admin.MemoryTelemetryStorage.CleanExpiredItems()
at KafkaFlow.Admin.MemoryTelemetryStorage.TryCleanItems()
at …
```
=> Fix MemoryTelemetryStorage concurrency issue

src/KafkaFlow.UnitTests/ConfigurationBuilders/ProducerConfigurationBuilderTests.cs, src/KafkaFlow/Extensions/ConfigurationBuilderExtensions.cs
We almost have had a problem with the storage of Kafka disks and when we were investigating the root cause, we found the configuration `compression.level` does not use the default value of producer configuration of confluent.
This has been tested in the development environment and unit tests.
=> fix(producer): use default value for compression level

website/docusaurus.config.js, website/src/pages/extensions/index.js
Create a page to list community extensions to KafkaFlow.
=> chore: add community extension page to website

.github/workflows/deploy-website.yml, README.md
- Trigger docs deploy once changes are in master instead of only on release since docs evolve at a different pace.
- Fix: broken build status link on the home page.
=> chore: trigger docs deploy once changes are in master

website/package.json, website/yarn.lock
Upgrade Docusaurus to the latest version (2.2.0).
=> chore: upgrade docusaurus to v2.2.0

src/KafkaFlow/Consumers/DistributionStrategies/BytesSumDistributionStrategy.cs
Fix NullReferenceException when stopping the bus. The previous fix (https://github.com/Farfetch/kafkaflow/pull/282) failed at actually fixing the issue.
When the cancellation token is cancelled, the `GetWorkerAsync` method is returning a null `Task` instead of a null value (`Task.FromResult((IWorker)null)`). The calling code is throwing the exception when calling `ConfigureAwait(false)` on the task.
Fixes #256 
Manually against a service where the integration tests were constantly throwing the exception on exit.
By sending us your contributions, you are agreeing that …
=> fix: fix NullReferenceException when stopping

website/src/pages/extensions/index.js
Add [KafkaFlow MessagePack Serializer](https://github.com/JotaDobleEse/kafkaflow-messagepack-serializer) to the extensions list.
Related to: https://github.com/Farfetch/kafkaflow/pull/336
=> docs: list messagepack serializer extension

src/KafkaFlow.BatchConsume/BatchConsumeMiddleware.cs, src/KafkaFlow.Serializer/DefaultTypeResolver.cs, src/KafkaFlow.Serializer/SerializerConsumerMiddleware.cs, src/KafkaFlow.TypedHandler/HandlerTypeMapping.cs, src/KafkaFlow.TypedHandler/TypedHandlerMiddleware.cs, src/KafkaFlow.UnitTests/Serializers/SerializerConsumerMiddlewareTests.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs
- Deserialize tombstone messages as a null object
- Better exception handling on consumer worker
- Fix #359
=> Proper tombstone message consumption and batch consume bug fixes

website/docs/guides/middlewares/batch-consume-middleware.md
Add BatchConsumeMiddleware page to docs, under the Middlewares category.
Fixes #357 
=> docs: add batch consume middleware page

website/src/pages/extensions/index.js
List extension [KafkaFlow.MediatR](https://github.com/gsferreira/kafkaflow-mediatr).
=> docs: add kafkaflow.mediatr to extension list

src/KafkaFlow/Clusters/ClusterManager.cs
When using `CreateTopicIfNotExists` for multiple topics if some of them already exists - KafkaFlow will throw exception because `CreateTopicsException` contains all results - successful and failed. `ClusterManager` perfrom check for `non expected errors` and mark success results as such.
It's easy to reproduce:
```cs
var servers = new[] { "127.0.0.1:9092" };
var topic = "TestTopic" + Guid.NewGuid();
// configure first bus to create main topic
var services = new ServiceCollection();
services
.AddKafka(
kafka => kafka
.UseConsoleLog()
.AddCluster(
cluster =>
{
cluster.WithBrokers(servers);
cluster.CreateTopicIfNotExists(topic, 4, 1);
}));
var serviceProvider = services.BuildServiceProvider();
var bus = serviceProvider.CreateKafkaBus();
Console.WriteLine("Start first bus");
await …
```
=> Remove exception when some topic are created and some are already exists

src/KafkaFlow.IntegrationTests/ProducerTest.cs, src/KafkaFlow/Producers/MessageProducer.cs, website/docs/guides/producers.md
Support publishing messages with `null` message key, so Kafka can use round-robin to pick partitions.
```csharp
await producer.ProduceAsync(null, message);
```
Fixes #373
Added an Integration Test.
=> fix: accept null as message key

src/KafkaFlow.IntegrationTests/ConsumerTest.cs, src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, src/KafkaFlow.UnitTests/ConfigurationBuilders/ConsumerConfigurationBuilderTests.cs, src/KafkaFlow/Configuration/ConsumerConfigurationBuilder.cs
`ConsumerConfig` was being referenced between consumers. This fix creates each consumer with `ConsumerConfig` in an isolated way.
fix https://github.com/Farfetch/kafkaflow/issues/410
=> [Bug Report]:  Kafkaflow does not allow to have consumers with different consumer groups

src/KafkaFlow.Serializer.JsonCore/JsonCoreSerializer.cs, src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj, src/KafkaFlow.UnitTests/Serializers/JsonCoreSerializerTests.cs
The reason why accented characters were being escaped was because the stream writer was escaping those characters.
The JsonCoreSerializer only accepted customization of JsonSerializerOptions and while this allows to prevent the escape of accented characters during the serialization process, nevertheless when writing the the steam the accented characters were still being escaped.
To fix this, it was added new constructors to JsonCoreSerializer to customize the JsonWriterOptions in order to allow to specify that accented characters should not be escaped when writing to the stream.
Fixes #414 
Unit tests were added to validate that the fix is working as expected.
-   [x] I have …
=> Support for customizing JsonWriterOptions in JsonCoreSerializer

src/KafkaFlow/Clusters/ClusterManager.cs
Pass security configuration to the `lazyAdminClientBuilder` 
Fixes #397 
=> fix: add security config to admin client builder

samples/KafkaFlow.Sample.BatchOperations/KafkaFlow.Sample.BatchOperations.csproj, samples/KafkaFlow.Sample.FlowControl/KafkaFlow.Sample.FlowControl.csproj, samples/KafkaFlow.Sample.PauseConsumerOnError/KafkaFlow.Sample.PauseConsumerOnError.csproj, samples/KafkaFlow.Sample.SchemaRegistry/KafkaFlow.Sample.SchemaRegistry.csproj, samples/KafkaFlow.Sample/KafkaFlow.Sample.csproj, src/Directory.Build.props, src/KafkaFlow.Admin.Dashboard/KafkaFlow.Admin.Dashboard.csproj, src/KafkaFlow.Admin.WebApi/KafkaFlow.Admin.WebApi.csproj, src/KafkaFlow.Admin/KafkaFlow.Admin.csproj, src/KafkaFlow.Extensions.Hosting/KafkaFlow.Extensions.Hosting.csproj, src/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj, src/KafkaFlow.LogHandler.Console/KafkaFlow.LogHandler.Console.csproj, src/KafkaFlow.LogHandler.Microsoft/KafkaFlow.LogHandler.Microsoft.csproj, src/KafkaFlow.Microsoft.DependencyInjection/KafkaFlow.Microsoft.DependencyInjection.csproj, src/KafkaFlow.Serializer.JsonCore/KafkaFlow.Serializer.JsonCore.csproj, src/KafkaFlow/KafkaFlow.csproj
- Upgrade Framework and Sample Projects to .NET 6
- Update C# language version from 9 to 10
Fixes #298  #322 
Ran both WebApi and Dashboard samples.
-   [x] I have added tests to cover my changes **(N/A?)**
-   [x] I have made corresponding changes to the documentation **(did not find any doc related to the .net versioning will be added in the release notes?)**
=> chore!: upgrade to .net 6

src/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj
The PR #295 introduced a conditional reference for macOS related to the issue [here](https://github.com/confluentinc/confluent-kafka-dotnet/issues/778#issuecomment-470276460).
Version [2.4.0](https://github.com/Farfetch/kafkaflow/releases/tag/2.4.0) updated confluent packages, eliminating this problem.
Fixes #458 
Try to reproduce the issue on macOS.
=> chore: remove conditional reference to librdkafka.redist

.github/workflows/metrics.yml
Keep track of metrics like:
- Average time to first response
- Average time to close 
- Number of items that remain open
- Number of items closed
- Total number of items created
The implementation uses [GitHub issue-metrics workflow](https://github.com/github/issue-metrics).
The GitHub Action will be executed on the first day of the month and generate 4 markdown files based on the last month's data:
1. Opened Items (contains PRs and Issues)
2. Closed Items (contains PRs and Issues)
3. Opened Discussions
4. Closed Discussions
The files will be attached to the GH Action as artifacts.
Due to the way that the Action works, we can't combine data into a single file.
**Manual Trigger:** It's possible to input the date range using the following format `2023-08-01..2023-08-31`. Leave it empty to …
=> Create GH Workflow to generate Metrics Reports

src/KafkaFlow.Abstractions/IMessageContext.cs, src/KafkaFlow.OpenTelemetry/ActivitySourceAccessor.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryConsumerEventsHandler.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryProducerEventsHandler.cs, src/KafkaFlow.UnitTests/BatchConsume/BatchConsumeMiddlewareTests.cs, src/KafkaFlow/Batching/BatchConsumeMessageContext.cs, src/KafkaFlow/Batching/BatchConsumeMiddleware.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/MessageContext.cs, src/KafkaFlow/Producers/MessageProducer.cs, website/docs/guides/global-events.md
- Include `peer.service` attribute in the Consumer and Producer spans.
- Closing the Consumer span when the `Complete()` method is invoked
Integration tests
=> Adapt OpenTelemetry to KafkaFlow 3.0

src/KafkaFlow.IntegrationTests/OpenTelemetryTests.cs, src/KafkaFlow.OpenTelemetry/ActivitySourceAccessor.cs, src/KafkaFlow.OpenTelemetry/KafkaFlowInstrumentation.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryConsumerEventsHandler.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryProducerEventsHandler.cs
Change how the exceptions are being recorded in OTEL activities to be in accordance with the official documentation:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/reporting-exceptions/README.md#option-4---use-activityrecordexception
Make the KafkaFlow ActivitySource name public so the users of manual instrumentation can easily refer to it without having to type it.
Example:
New:
```csharp
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
.AddSource(KafkaFlowInstrumentation.ActivitySourceName)
.Build();
```
Old:
```csharp
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
.AddSource("KafkaFlow.OpenTelemetry")
.Build();
```
The current tests already validate the changes.
-   [x] I …
=> feat: upgrade exception events for OpenTelemetry

website/docs/guides/migration/_category_.json, website/docs/guides/migration/from-v2-to-v3.md
Adding migration guide from v2 to v3
Fixes #304
NA
=> Migration guide from v2 to v3

website/docusaurus.config.js, website/src/components/Community/Resource/Index.js, website/src/pages/community/index.js
Create a page to track community resources such as videos, articles, podcasts, conference talks, meetups, etc.
The goal is to create a central repository where the community can not only promote resources but also find useful information when learning KafkaFlow.
=> docs: community resources page

KafkaFlow.sln, samples/KafkaFlow.Sample.OpenTelemetry/KafkaFlow.Sample.OpenTelemetry.csproj, samples/KafkaFlow.Sample.OpenTelemetry/PrintConsoleHandler.cs, samples/KafkaFlow.Sample.OpenTelemetry/Program.cs, samples/KafkaFlow.Sample.OpenTelemetry/README.md, samples/KafkaFlow.Sample.OpenTelemetry/TestMessage.cs, website/docs/getting-started/samples.md, website/docs/guides/dependency-injection.md, website/docs/guides/migration/_category_.json, website/docs/guides/open-telemetry.md, website/docs/introduction.md, website/package-lock.json, website/yarn.lock
Create a sample on how to enable OpenTelemetry instrumentation.
Other:
- Review menu order to keep migrations as the final entry.
Related to #451
- Run sample.
=> docs: sample otel

samples/KafkaFlow.Sample.ConsumerThrottling/KafkaFlow.Sample.ConsumerThrottling.csproj, samples/KafkaFlow.Sample.Dashboard/KafkaFlow.Sample.Dashboard.csproj, samples/KafkaFlow.Sample.WebApi/KafkaFlow.Sample.WebApi.csproj, samples/KafkaFlow.Sample/KafkaFlow.Sample.csproj, src/KafkaFlow.Admin.Dashboard/KafkaFlow.Admin.Dashboard.csproj, src/KafkaFlow.Admin/KafkaFlow.Admin.csproj, src/KafkaFlow.Compressor.Gzip/KafkaFlow.Compressor.Gzip.csproj, src/KafkaFlow.OpenTelemetry/KafkaFlowInstrumentation.cs, src/KafkaFlow.SchemaRegistry/KafkaFlow.SchemaRegistry.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson/KafkaFlow.Serializer.SchemaRegistry.ConfluentJson.csproj, src/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf/KafkaFlow.Serializer.SchemaRegistry.ConfluentProtobuf.csproj, src/KafkaFlow.Unity/KafkaFlow.Unity.csproj, src/KafkaFlow/KafkaFlow.csproj, tests/KafkaFlow.IntegrationTests/KafkaFlow.IntegrationTests.csproj, tests/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj
This refactor aims to remove unused references.
Builds with success
=> refactor: unused references cleanup

src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/IConsumer.cs, src/KafkaFlow/Consumers/IConsumerWorker.cs, src/KafkaFlow/Consumers/OffsetCommitter.cs, src/KafkaFlow/Event.cs, src/KafkaFlow/Extensions/ChannelExtensions.cs, src/KafkaFlow/Extensions/MessageContextExtensions.cs, src/KafkaFlow/Extensions/TaskExtensions.cs, src/KafkaFlow/KafkaFlow.csproj, tests/KafkaFlow.UnitTests/OffsetCommitterTests.cs
Implemented synchronization mechanisms for immediate consumer shutdown upon partition revocation, triggered by exceeding the 'max poll interval'. Additionally, integrated the 'stop worker timeout' configuration to effectively cancel ongoing message processing when a stop request is issued, ensuring a smooth and non-blocking stop procedure.
Fixes #492 
Manual and automated tests
By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/CO …
=> fix: consumer never stops when max poll is exceeded

src/KafkaFlow/Consumers/DistributionStrategies/BytesSumDistributionStrategy.cs, src/KafkaFlow/Consumers/DistributionStrategies/PartitionKeyDistributionStrategy.cs, tests/KafkaFlow.UnitTests/Consumer/DistributionStrategies/BytesSumDistributionStrategyTests.cs, tests/KafkaFlow.UnitTests/Consumer/DistributionStrategies/PartitionKeyDistributionStrategyTests.cs, tests/KafkaFlow.UnitTests/Factories/WorkerFactory.cs
The default worker distribution strategy uses the message key to distribute messages to consumers.
While the message key is the default partition strategy, it is not guaranteed the producer is using that strategy and can have implications in guaranteeing the message order when consuming messages.
This PR adds a new worker distribution strategy based on the partition key instead which better guarantees the message order.
Fixes #490 #440
Unit tests were added
By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our …
=> Add distribution strategy from partition key

src/KafkaFlow.Admin.Dashboard/KafkaFlow.Admin.Dashboard.csproj
The removal of `Microsoft.Extensions.FileProviders.Embedded` in [MR-486](https://github.com/Farfetch/kafkaflow/pull/486/files) caused an exception for assembly 'KafkaFlow.Admin.Dashboard' when using the [ManifestEmbeddedFileProvider](https://github.com/Farfetch/kafkaflow/blob/e2c21c0410d8f02d3292df1ad5d677c99329bae4/src/KafkaFlow.Admin.Dashboard/ApplicationBuilderExtensions.cs#L46) to get the provider.
> System.InvalidOperationException: Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'KafkaFlow.Admin.Dashboard'.
This package has been added again in the current MR.
Fixes #497 
The dashboard project runs successfully without throwing any exceptions.
-   [x] I have …
=> fix: add Microsoft.Extensions.FileProviders.Embedded package

samples/KafkaFlow.Sample.WebApi/KafkaFlow.Sample.WebApi.csproj
The reference to the Admin.WebApi project was removed as part of PR #486. Because of that, the added Controllers are not picked when generating the OpenApi Specification.
Fixes #502 
Run the sample. Observe Swagger API specification.
=> fix: add missing reference to webapi sample #502

.github/workflows/deploy-website.yml, .github/workflows/test-deploy-website.yml, website/docs/guides/admin/dashboard.md, website/docs/guides/global-events.md, website/docs/guides/middlewares/serializer-middleware.md, website/docusaurus.config.js, website/package.json, website/versioned_docs/version-2.x/guides/admin/dashboard.md, website/versioned_docs/version-2.x/guides/global-events.md, website/versioned_docs/version-2.x/guides/middlewares/serializer-middleware.md, website/yarn.lock
Migrate docusaurus to v3
Fixes #510 
=> chore(deps): migrate docusaurus to v3

src/KafkaFlow/KafkaFlow.csproj
The `Microsoft.IO.RecyclableMemoryStream` package was updated to Version 3.0.0.
Fixes #504
Ran the sample, with a Microsoft.IO.RecyclableMemoryStream 3.0.0 installed, and produced a message without exceptions thrown.
=> fix: bump microsoft.io.recyclablememorystream from 2.3.2 to 3.0.0 #504

website/docs/guides/consumers/add-consumers.md, website/docs/guides/migration/from-v2-to-v3.md
Changes only in the documentation
Added information about new methods that exists in V3 nuget, but not existed before and which old methods they are replacement.
=> docs: Add information about new methods

website/docs/guides/middlewares/middlewares.md
Hi, I discovered your library recently and was going through the docs and copying examples, and found a small typo which makes the sample code not compile.
Copied the [correct name](https://learn.microsoft.com/en-us/dotnet/api/system.invalidoperationexception) from Visual Studio.
=> docs: fix typo in middlewares.md - InvalidOperationException incorrectly spelled with lowercase 'o'

website/docs/getting-started/installation.md, website/docs/guides/admin/web-api.md, website/docs/guides/consumers/dynamic-workers-configuration.md, website/docs/guides/middlewares/middlewares.md, website/docs/guides/middlewares/serializer-middleware.md
Fixed some typos in the documentation.
N/A
=> fix: documentation typos

src/KafkaFlow/MessageContext.cs, tests/KafkaFlow.UnitTests/MessageContextTests.cs
When the message context is changed by using `SetMessage`, the `Items` on the context are lost. This change preserves the original `Items`
I added a unit test
=> fix: preserve message context items when SetMessage is called

samples/KafkaFlow.Sample.OpenTelemetry/Program.cs, src/KafkaFlow.OpenTelemetry/ExtensionMethods.cs, src/KafkaFlow.OpenTelemetry/KafkaFlowInstrumentationOptions.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryConsumerEventsHandler.cs, src/KafkaFlow.OpenTelemetry/OpenTelemetryProducerEventsHandler.cs, tests/KafkaFlow.IntegrationTests/OpenTelemetryTests.cs, website/docs/guides/open-telemetry.md
Adds producer and consumer enrichers for OpenTelemetry instrumentation
Closes #465
Include integration tests for producer enricher and consumer enricher
=> feat: add producer and consumer enricher for OpenTelemetry instrumentation

src/KafkaFlow/Configuration/KafkaConfigurationBuilder.cs
`IClusterManagerAccessor` is already registered as a singleton a few lines above.
Looks like this line was accidentally duplicated in https://github.com/Farfetch/kafkaflow/commit/3f996b61bd2850fbe7cd5893bae54b78521ae74c#diff-ad7219aa5db9d536244342b218fd6ef245e685445e173b747ef99513d520dbc4R52
The duplicate registration breaks our Ninject DI implementation:
```
Ninject.ActivationException : Error activating IConsumerManagerFactory
More than one matching bindings are available.
Matching bindings:
1) binding from IConsumerManagerFactory to constant value
2) binding from IConsumerManagerFactory to constant value
Activation path:
1) Request for IConsumerManagerFactory
Suggestions:
1) Ensure that you have defined a binding for IConsumerManagerFactory only once.
```
Please describe the tests that …
=> fix: remove duplicate DI registration of IClusterManagerAccessor

src/KafkaFlow.Admin.Dashboard/ClientApp/package-lock.json
This PR solves the following KafkaFlow.Admin.Dashboard vulnerabilities:
- https://github.com/Farfetch/kafkaflow/security/dependabot/83
- https://github.com/Farfetch/kafkaflow/security/dependabot/97
- https://github.com/Farfetch/kafkaflow/security/dependabot/101
1. Changed [environment.ts](https://github.com/Farfetch/kafkaflow/blob/master/src/KafkaFlow.Admin.Dashboard/ClientApp/src/environments/environment.ts) to http://localhost:63128/kafkaflow
2. Added the following CORS on [KafkaFlow.Sample.Dashboard](https://github.com/Farfetch/kafkaflow/blob/master/samples/KafkaFlow.Sample.Dashboard/Startup.cs)
```csharp
const string MyAllowSpecificOrigins = "_myAllowSpecificOrigins";
services.AddCors(c =>
{
c.AddPolicy(MyAllowSpecificOrigins, options =>
options.AllowAnyMethod()
.AllowAnyHeader() …
```
=> fix: kafkaflow admin dashboard vulnerabilities

src/KafkaFlow.Abstractions/ILogHandler.cs, src/KafkaFlow.Abstractions/NullLogHandler.cs, src/KafkaFlow.Admin/TelemetryScheduler.cs, src/KafkaFlow.LogHandler.Console/ConsoleLogHandler.cs, src/KafkaFlow.LogHandler.Microsoft/MicrosoftLogHandler.cs, tests/KafkaFlow.IntegrationTests/Core/TraceLogHandler.cs, tests/KafkaFlow.UnitTests/LogHandlers/MicrosoftLogHandlerTests.cs
Avoid rethrow exception when there are errors on serialize exception data
Closes #537 
=> fix: does not serialize exception in ProduceTelemetry

src/KafkaFlow/Middlewares/Serializer/SerializerProducerMiddleware.cs, tests/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs, tests/KafkaFlow.IntegrationTests/Core/Handlers/MessageStorage.cs, tests/KafkaFlow.IntegrationTests/Core/Handlers/NullMessageHandler.cs, tests/KafkaFlow.IntegrationTests/Core/Producers/NullProducer.cs, tests/KafkaFlow.IntegrationTests/ProducerTest.cs, tests/KafkaFlow.UnitTests/Serializers/SerializerProducerMiddlewareTests.cs, website/docs/guides/middlewares/serializer-middleware.md
Adds support for tombstone records production.
Fixes https://github.com/Farfetch/kafkaflow/issues/516
This was tested via the provided unit and integration tests.
=> fix: produce tombstone records

src/KafkaFlow.Abstractions/Configuration/IClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, tests/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs
If passing `-1` for `NumPartitions` or `ReplicationFactor` when creating topics, the creation will use the cluster-default values for these values. This change allows for defaulting to using cluster values, and over-riding them if required. This reduces a lot of boilerplate code when setting up a cluster in code.
Added integration tests to test this against a Kafka instance.
By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.m …
=> feat: allow use of cluster defined values for topic creation

src/KafkaFlow/KafkaBus.cs
There are certain cases when `StopAsync` is called multiple times on different threads, which presents itself as the `StopAsync` call hanging indefinitely. This change adds thread protection to ensure that `StopAsync` is only called once.
An example of when this occurs is [here ](https://github.com/dotnet/aspnetcore/issues/40271) when using WebApplicationFactory<> for testing.
I've run this in a local unit test scenario against a real Kafka instance to ensure that the teardown is clean and handles multiple concurrent calls to `StopAsync`.
By sending us your …
=> fix: prevent hanging if stop called from multiple threads

src/KafkaFlow/Batching/BatchConsumeMiddleware.cs, src/KafkaFlow/Clusters/ClusterManager.cs, src/KafkaFlow/Consumers/Consumer.cs, src/KafkaFlow/Consumers/ConsumerManager.cs, src/KafkaFlow/Consumers/ConsumerWorker.cs, src/KafkaFlow/Consumers/ConsumerWorkerPool.cs, src/KafkaFlow/Consumers/WorkerPoolFeeder.cs, src/KafkaFlow/Consumers/WorkersBalancers/ConsumerLagWorkerBalancer.cs, src/KafkaFlow/Extensions/ChannelExtensions.cs, src/KafkaFlow/Extensions/TaskExtensions.cs, src/KafkaFlow/KafkaBus.cs, src/KafkaFlow/Middlewares/ConsumerThrottling/ConsumerThrottlingThreshold.cs, src/KafkaFlow/Middlewares/Serializer/DeserializerConsumerMiddleware.cs, src/KafkaFlow/Middlewares/Serializer/SerializerProducerMiddleware.cs, src/KafkaFlow/Producers/MessageProducer.cs
Use `ConfigureAwait(false)` on all awaits. This was already present on some awaits in KafkaFlow, but applied inconsistently.
This allows awaits to continue without forcing the callback to be invoked on the original context or scheduler. This can improve performance and help prevent deadlocks when used in environments with a `SynchronizationContext` such as ASP .NET Framework or UI applications.
This seems to be best practice in libraries (even if it unfortunately makes async code less simple / clean):
- https://devblogs.microsoft.com/dotnet/configureawait-faq/
- https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html
- https://blog.stephencleary.com/2023/11/configureawait-in-net-8.html
Fixes #563
We stopped experiencing stalls in Kafka message consumption in ASP …
=> fix: use ConfigureAwait(false) on all awaits

src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, tests/KafkaFlow.IntegrationTests/GlobalEventsTest.cs
As reported in issue #569 OnStarted and OnStoppind didn't allow for registering multiple callbacks for the same event. By combining the registration of callbacks this fixes the issue.
Fixes #569
Integration Tests added.
=> Allow multiple OnStarted and OnStopping callbacks

src/KafkaFlow/Consumers/Consumer.cs
Call the registered revoke handlers before stopping the ConsumerFlowManager.
Fixes #581
Against the provided [code reproducing the problem](https://github.com/Farfetch/kafkaflow-retry-extensions/issues/151).
=> fix: stop flow manager after calling revoke handlers

src/KafkaFlow/Producers/MessageProducer.cs
=> fix: production delivery result errors

Makefile, src/KafkaFlow.Abstractions/Configuration/IClusterConfigurationBuilder.cs, src/KafkaFlow/Clusters/ClusterManager.cs, src/KafkaFlow/Configuration/ClusterConfigurationBuilder.cs, src/KafkaFlow/Configuration/TopicConfiguration.cs
Passes additional configuration options, if present, to the topic creation method.
Fixes #600 
=> feat: Create topic with additional configuration if present

src/KafkaFlow.OpenTelemetry/ActivitySourceAccessor.cs
The current code in main branch wrongly replaced `messaging.system` with `messaging.type`. This PR reverts that change
https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/
=> fix: replace `messaging.type` with `messaging.system` in generic tags
